### ISSUE TITLE
string building is O(n*n)

### ISSUE THREAD

**Issue by williballenthin** [osardar/sha256#10]
this isn't a rust thing. doing `string += string` in a loop is accidentally O(n*n) due to reallocation of the underlying string:

https://github.com/osardar/sha256/blob/bceb018ac04ce82c03f4a2e1fec791579947bc4f/src/lib.rs#L174-L176

maybe build the parts in a `Vec<String>` and then join them once.

**Comment by osardar** [comment]
I switched up the syntax & used `map/collect`, but it doesn't seem to me that I broke out of O(n*n) since I'm still using `format!` to generate the hex conversion. I couldn't seem to find a native way to convert a u8 to a hex str unfortunately- do you happen to know of any?

https://github.com/osardar/sha256/blob/de07efd847608e3c23e2711e27db39ca69983744/src/lib.rs#L164-L167

**Comment by williballenthin** [comment]
The performance bug is in the repeated allocation and copying of strings as the intermediate results are constructed. The new code looks great! You can’t really avoid the format calls unless you maintain a lookup table mapping bytes to their rendered representations (not a bad idea but not worth it here for 64 characters). 

Details here:

https://ericlippert.com/2013/06/24/string-concatenation-behind-the-scenes-part-two/amp/
